version: "3.9"
services:
  supabase-mcp:
    image: ghcr.io/supabase-community/supabase-mcp:latest
    container_name: supabase-mcp
    ports: ["9103:3000"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5