version: "3.9"
services:
  ollama-mcp:
    image: ghcr.io/ollama/ollama-mcp:latest
    container_name: ollama-mcp
    volumes:
      - ./models:/root/.ollama
    ports: ["9108:11434"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 5
