version: "3.9"
services:
  zotero-mcp:
    image: ghcr.io/kaliaboi/zotero-mcp-server:latest
    container_name: zotero-mcp
    ports: ["9107:8082"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 30s
      timeout: 10s
      retries: 5